stages:
  - publish
pages:
  stage: publish
  image: registry.git.mpib-berlin.mpg.de/neurocode/git-workshop/xaringan:latest
  script:
    - Rscript -e "rmarkdown::render('index.Rmd', 'all', output_dir = 'public', output_file = 'index.html')"
  artifacts:
    paths:
      - public
  only:
    # note that this should be replaced with master once all the different documents are merged:
    - git-advanced