image: python:3
variables:
  GIT_SUBMODULE_STRATEGY: recursive
pages:
  stage: deploy
  script:
    - mkdir public
    - mv index.html public/index.html
    - mv revealjs public/revealjs
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  only:
  - master
